-- DRAFT — DO NOT RUN IN PRODUCTION
-- Suggestion, review, impact and immutable merge/reversal ledger. No automatic merge procedure is created.

CREATE TABLE IF NOT EXISTS customer_duplicate_candidates (
  id CHAR(36) NOT NULL,
  candidate_ref VARCHAR(64) NOT NULL,
  customer_a_id CHAR(36) NOT NULL,
  customer_b_id CHAR(36) NOT NULL,
  confidence VARCHAR(16) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'suggested_duplicate',
  rule_version VARCHAR(32) NOT NULL,
  reasons JSON NOT NULL,
  conflicts JSON NOT NULL,
  source_snapshot VARCHAR(128) NOT NULL,
  first_suggested_at DATETIME(6) NOT NULL,
  last_evaluated_at DATETIME(6) NOT NULL,
  reviewed_by VARCHAR(128) NULL,
  reviewed_at DATETIME(6) NULL,
  review_reason VARCHAR(500) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  CONSTRAINT customer_duplicate_candidates_a_fk FOREIGN KEY (customer_a_id) REFERENCES customer_masters(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT customer_duplicate_candidates_b_fk FOREIGN KEY (customer_b_id) REFERENCES customer_masters(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT customer_duplicate_candidates_pair_ck CHECK (customer_a_id < customer_b_id),
  CONSTRAINT customer_duplicate_candidates_confidence_ck CHECK (confidence IN ('high','medium','low')),
  CONSTRAINT customer_duplicate_candidates_status_ck CHECK (status IN ('suggested_duplicate','under_review','confirmed_same_customer','confirmed_different_customer','merged','merge_reversed','deferred')),
  UNIQUE KEY customer_duplicate_candidates_ref_uq (candidate_ref),
  UNIQUE KEY customer_duplicate_candidates_pair_uq (customer_a_id, customer_b_id, rule_version, source_snapshot),
  INDEX customer_duplicate_candidates_queue_idx (status, confidence, first_suggested_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS customer_merge_history (
  id CHAR(36) NOT NULL,
  merge_ref VARCHAR(64) NOT NULL,
  duplicate_candidate_id CHAR(36) NOT NULL,
  event_type VARCHAR(32) NOT NULL,
  survivor_customer_master_id CHAR(36) NOT NULL,
  absorbed_customer_master_id CHAR(36) NOT NULL,
  previous_merge_event_id CHAR(36) NULL,
  policy_version VARCHAR(32) NOT NULL,
  source_snapshot VARCHAR(128) NOT NULL,
  evidence_snapshot JSON NOT NULL,
  impact_before JSON NOT NULL,
  impact_after JSON NULL,
  expected_row_counts JSON NOT NULL,
  actual_row_counts JSON NULL,
  approved_by VARCHAR(128) NOT NULL,
  executed_by VARCHAR(128) NULL,
  reason VARCHAR(500) NOT NULL,
  approved_at DATETIME(6) NOT NULL,
  executed_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  CONSTRAINT customer_merge_history_candidate_fk FOREIGN KEY (duplicate_candidate_id) REFERENCES customer_duplicate_candidates(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT customer_merge_history_survivor_fk FOREIGN KEY (survivor_customer_master_id) REFERENCES customer_masters(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT customer_merge_history_absorbed_fk FOREIGN KEY (absorbed_customer_master_id) REFERENCES customer_masters(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT customer_merge_history_previous_fk FOREIGN KEY (previous_merge_event_id) REFERENCES customer_merge_history(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT customer_merge_history_distinct_ck CHECK (survivor_customer_master_id <> absorbed_customer_master_id),
  CONSTRAINT customer_merge_history_event_ck CHECK (event_type IN ('merge_approved','merge_executed','merge_reversed')),
  UNIQUE KEY customer_merge_history_ref_uq (merge_ref),
  INDEX customer_merge_history_survivor_idx (survivor_customer_master_id, created_at),
  INDEX customer_merge_history_absorbed_idx (absorbed_customer_master_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
