import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/AdminShell";
import { HiringActionCentre } from "@/components/admin/HiringActionCentre";
import { AdminMetricCard, AdminPanel, AdminStatusBadge } from "@/components/admin/AdminPrimitives";
import { canManageSmartHiring } from "@/lib/admin/permissions";
import { requireAdminSession } from "@/lib/admin/session";
import { getHiringAdminSnapshot } from "@/lib/hiring/admin";
import { hiringRoleLabel } from "@/lib/hiring/domain";
import { getHiringFeatureState } from "@/lib/hiring/feature-flags";
export const metadata: Metadata = { title: "Smart Hiring | WriteX Admin", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";
export default async function HiringOverviewPage() { const session=await requireAdminSession(); if(!canManageSmartHiring(session)) notFound(); const [snapshot,flags]=await Promise.all([getHiringAdminSnapshot(),Promise.resolve(getHiringFeatureState())]); const c=snapshot.counts; return <AdminShell session={session} eyebrow="Smart Hiring" title="Hiring command centre" description="Actionable recruitment, assessment, integrity and verification queues. All public modules remain controlled by feature flags.">
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><AdminMetricCard label="New applications" value={c.application_received||0} href="/admin/hiring/applications" priority="action" /><AdminMetricCard label="Eligibility pending" value={c.eligibility_review||0} href="/admin/hiring/applications" /><AdminMetricCard label="Assessments submitted" value={c.assessment_submitted||0} href="/admin/hiring/assessments" /><AdminMetricCard label="Connected reviews" value={snapshot.connectedReviewCount} href="/admin/hiring/connected-candidates" priority={snapshot.connectedReviewCount?"action":"normal"} /><AdminMetricCard label="Interviews today" value={c.interview_scheduled||0} href="/admin/hiring/applications" /><AdminMetricCard label="Offers pending" value={c.selected||0} href="/admin/hiring/applications" /><AdminMetricCard label="Talent pool" value={c.talent_pool||0} href="/admin/hiring/applications" /><AdminMetricCard label="Verification queue" value={snapshot.verificationCases.length} href="/admin/hiring/verification-centre" /></div>
  <div className="mt-6"><AdminPanel title="Needs Attention" description="Prioritised human-review queues with a direct destination and no automatic candidate decisions."><HiringActionCentre snapshot={snapshot}/></AdminPanel></div>
  <div className="mt-6"><AdminPanel title="Upcoming" description="Scheduled candidate work that the hiring team should prepare for next.">{snapshot.interviews.filter(item=>item.status==="scheduled"||item.status==="rescheduled").length?<div className="grid gap-3">{snapshot.interviews.filter(item=>item.status==="scheduled"||item.status==="rescheduled").slice(0,6).map(item=><Link key={item.id} href={`/admin/hiring/applications/${encodeURIComponent(item.applicationReference)}`} className="grid gap-2 rounded-md border border-wxBorder p-4 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="font-bold text-wxIndigo900">{item.applicationReference}</p><p className="mt-1 text-sm text-wxIndigo500">{item.type.replace(/_/g," ")} / {item.scheduledAt?new Date(item.scheduledAt).toLocaleString("en-IN"):"Schedule needs confirmation"}</p></div><AdminStatusBadge tone="info">{item.status.replace(/_/g," ")}</AdminStatusBadge></Link>)}</div>:<p className="text-sm text-wxIndigo500">No interviews are currently scheduled.</p>}</AdminPanel></div>
  <div className="mt-6"><AdminPanel title="Recent application activity" description="Latest genuine submissions with their current stage and internal notification state.">{snapshot.applications.length?<div className="grid gap-3">{snapshot.applications.slice(0,6).map(item=><Link key={item.reference} href={`/admin/hiring/applications/${encodeURIComponent(item.reference)}`} className="grid gap-3 rounded-md border border-wxBorder p-4 transition hover:border-wxViolet700 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><p className="font-bold text-wxIndigo900">{item.reference}</p><p className="mt-1 text-sm text-wxIndigo500">{hiringRoleLabel(item.role)} / {new Date(item.submittedAt).toLocaleString("en-IN")}</p></div><AdminStatusBadge tone={item.stage==="application_received"?"info":"neutral"}>{item.stage.replace(/_/g," ")}</AdminStatusBadge><AdminStatusBadge tone={item.notificationStatus==="sent"?"success":item.notificationStatus==="failed"||item.notificationStatus==="unavailable"?"warning":"neutral"}>{item.notificationStatus.replace(/_/g," ")}</AdminStatusBadge></Link>)}</div>:<p className="text-sm text-wxIndigo500">No applications have been submitted.</p>}</AdminPanel></div>
  <div className="mt-6 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><AdminPanel title="Hiring funnel" description="Counts are operational records, not decorative estimates."><div className="grid gap-2 sm:grid-cols-3 lg:grid-cols-6">{[["Applications",c.application_received],["Eligible",c.eligibility_review],["Assessment",c.assessment_submitted],["Shortlisted",c.shortlisted],["Interview",c.interview_completed],["Joined",c.joined]].map(([label,value])=><div key={String(label)} className="rounded-md bg-wxSurfaceSoft p-3"><p className="text-xs text-wxIndigo500">{label}</p><p className="mt-1 text-xl font-bold">{Number(value)||0}</p></div>)}</div></AdminPanel><AdminPanel title="Activation status" description="No public hiring route is enabled without explicit approval."><div className="grid gap-3 text-sm">{Object.entries(flags).map(([key,value])=><div key={key} className="flex items-center justify-between gap-3"><span className="capitalize text-wxIndigo600">{key.replace(/([A-Z])/g," $1")}</span><AdminStatusBadge tone={value===true||value==="api"?"success":"neutral"}>{String(value)}</AdminStatusBadge></div>)}</div></AdminPanel></div>
  <div className="mt-6 grid gap-4 md:grid-cols-3"><Link className="rounded-lg border border-wxBorder bg-white p-5 font-bold shadow-soft hover:border-wxViolet700" href="/admin/hiring/question-bank">Manage question bank</Link><Link className="rounded-lg border border-wxBorder bg-white p-5 font-bold shadow-soft hover:border-wxViolet700" href="/admin/hiring/verification-centre">Open Verification Centre</Link><Link className="rounded-lg border border-wxBorder bg-white p-5 font-bold shadow-soft hover:border-wxViolet700" href="/admin/hiring/connected-candidates">Review connected candidates</Link></div>
  </AdminShell>; }
