"use client";

import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { Calculator, CheckCircle2, Gavel, UserCheck } from "lucide-react";

async function runOperation(body:Record<string,unknown>){
  const response=await fetch("/api/admin/hiring/operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});
  const payload=await response.json().catch(()=>null);
  if(!response.ok)throw new Error(payload?.error?.message||"The hiring action could not be completed.");
  return payload.data;
}

export function CandidateReviewControls({applicationReference,systemRecommendation,hasAdminReview,hasFinalDecision,finalDecisionReady}:{applicationReference:string;systemRecommendation:string|null;hasAdminReview:boolean;hasFinalDecision:boolean;finalDecisionReady:boolean}){
  const router=useRouter();const[state,setState]=useState<"idle"|"busy"|"success"|"error">("idle");const[message,setMessage]=useState("");
  async function execute(body:Record<string,unknown>){setState("busy");setMessage("");try{await runOperation(body);setState("success");setMessage("Saved to the candidate audit trail.");router.refresh();}catch(error){setState("error");setMessage(error instanceof Error?error.message:"The hiring action could not be completed.");}}
  function adminReview(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);void execute({resource:"admin_review",applicationReference,decision:form.get("decision"),adminScore:form.get("adminScore")?Number(form.get("adminScore")):undefined,structuredNotes:{strengths:String(form.get("strengths")||""),risks:String(form.get("risks")||"")},notes:form.get("notes"),recommendationAction:form.get("recommendationAction"),overrideReason:form.get("overrideReason")||undefined,reason:form.get("reason")});}
  function finalDecision(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);void execute({resource:"final_decision",applicationReference,outcome:form.get("outcome"),reason:form.get("reason"),explicitConfirmation:form.get("explicitConfirmation")==="on"});}
  return <div className="grid gap-6" id="candidate-review-actions">
    <section className="rounded-md border border-wxBorder bg-wxSurface p-5"><div className="flex items-start gap-3"><Calculator className="mt-0.5 h-5 w-5 text-wxViolet700"/><div><h2 className="font-bold text-wxIndigo900">System Review</h2><p className="mt-1 text-sm leading-6 text-wxIndigo500">Recalculate the independent rules-based review from the locked eligibility, assessment and integrity evidence.</p></div></div><button type="button" disabled={state==="busy"} onClick={()=>void execute({resource:"system_review",applicationReference,action:"recalculate",reason:"Admin requested a fresh System Review from the current locked evidence."})} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-md border border-wxBorder px-4 text-sm font-bold text-wxViolet700"><Calculator className="h-4 w-4"/>Run System Review</button></section>
    <form onSubmit={adminReview} className="rounded-md border border-wxBorder bg-wxSurface p-5"><div className="flex items-start gap-3"><UserCheck className="mt-0.5 h-5 w-5 text-wxViolet700"/><div><h2 className="font-bold text-wxIndigo900">Admin Review</h2><p className="mt-1 text-sm leading-6 text-wxIndigo500">Record the human decision independently. Current System recommendation: <strong>{systemRecommendation?.replace(/_/g," ")||"not available"}</strong>.</p></div></div><div className="mt-4 grid gap-4 sm:grid-cols-3"><Select name="decision" label="Admin decision" values={["accept","reject","hold","talent_pool","request_reassessment","request_viva"]}/><Select name="recommendationAction" label="Relationship to System Review" values={["confirm","override","independent"]}/><Field name="adminScore" label="Admin score (optional)" type="number"/></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field name="strengths" label="Strengths" textarea/><Field name="risks" label="Risks or attention points" textarea/></div><Field name="notes" label="Admin review notes" textarea/><Field name="overrideReason" label="Override reason (mandatory when overriding)" textarea/><Field name="reason" label="Audit reason" required/><button disabled={state==="busy"||!systemRecommendation} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-md bg-brand-spectrum px-5 text-sm font-bold text-white disabled:opacity-50"><CheckCircle2 className="h-4 w-4"/>Record Admin Review</button></form>
    <form onSubmit={finalDecision} className="rounded-md border border-wxBorder bg-wxSurface p-5"><div className="flex items-start gap-3"><Gavel className="mt-0.5 h-5 w-5 text-wxViolet700"/><div><h2 className="font-bold text-wxIndigo900">Final Decision</h2><p className="mt-1 text-sm leading-6 text-wxIndigo500">The authorised Admin owns the final outcome. This action is separate from System Review and Admin Review.</p></div></div>{hasFinalDecision?<p className="mt-4 rounded-md border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-900">The final decision is already recorded. Review the Decision and History sections for its audited evidence.</p>:hasAdminReview&&!finalDecisionReady?<p className="mt-4 rounded-md border border-amber-200 bg-amber-50 p-3 text-sm font-semibold text-amber-900">Complete the required Viva or interview before recording the Final Decision.</p>:null}<div className="mt-4 grid gap-4 sm:grid-cols-2"><Select name="outcome" label="Final outcome" values={["selected","rejected","talent_pool","hold","offer_released"]}/><Field name="reason" label="Final decision reason" required/></div><label className="mt-4 flex items-start gap-3 rounded-md border border-wxBorder bg-wxSurfaceSoft p-3 text-sm font-semibold text-wxIndigo700"><input name="explicitConfirmation" type="checkbox" required className="mt-1 h-4 w-4"/>I confirm this final hiring decision and understand that candidate communication and stage history may be updated.</label><button disabled={state==="busy"||hasFinalDecision||!hasAdminReview||!finalDecisionReady} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-md bg-wxIndigo900 px-5 text-sm font-bold text-white disabled:opacity-50"><Gavel className="h-4 w-4"/>Record Final Decision</button></form>
    {message?<p role={state==="error"?"alert":"status"} className={`rounded-md border p-3 text-sm font-semibold ${state==="error"?"border-red-200 bg-red-50 text-red-800":"border-emerald-200 bg-emerald-50 text-emerald-800"}`}>{message}</p>:null}
  </div>;
}

function Field({name,label,required=false,textarea=false,type="text"}:{name:string;label:string;required?:boolean;textarea?:boolean;type?:string}){const className="mt-2 min-h-11 w-full rounded-md border border-wxBorder bg-wxSurface px-3 py-2 text-sm text-wxIndigo900";return <label className="mt-4 block text-sm font-bold text-wxIndigo800">{label}{textarea?<textarea name={name} required={required} rows={3} className={className}/>:<input name={name} required={required} type={type} min={type==="number"?0:undefined} max={type==="number"?100:undefined} className={className}/>}</label>}
function Select({name,label,values}:{name:string;label:string;values:string[]}){return <label className="text-sm font-bold text-wxIndigo800">{label}<select name={name} className="mt-2 min-h-11 w-full rounded-md border border-wxBorder bg-wxSurface px-3 text-sm text-wxIndigo900">{values.map(value=><option key={value} value={value}>{value.replace(/_/g," ")}</option>)}</select></label>}
