"use client";

import { useState, type FormEvent } from "react";
import { ClipboardCheck } from "lucide-react";

const options=["needs_development","acceptable","strong"] as const;
export function SalesVideoReviewForm({applicationReference,candidateFileId,initialReview}:{applicationReference:string;candidateFileId:string;initialReview?:Record<string,unknown>|null}){
  const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const form=new FormData(event.currentTarget);const response=await fetch("/api/admin/hiring/video-reviews",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({applicationReference,candidateFileId,...Object.fromEntries(form)})});const payload=await response.json();setBusy(false);if(!response.ok){setMessage(payload.error?.message||"The video review could not be saved.");return;}setMessage("Structured human video review saved and audited.");window.setTimeout(()=>window.location.reload(),500);}
  return <form onSubmit={submit} className="mt-4 grid gap-4 rounded-md border border-wxBorder bg-wxSurfaceSoft p-4"><div className="flex gap-3"><ClipboardCheck className="h-5 w-5 shrink-0 text-wxViolet700"/><div><p className="font-semibold text-wxIndigo900">Structured human video review</p><p className="mt-1 text-xs leading-5 text-wxIndigo500">Assess job-relevant spoken evidence only. Do not infer personality, health, ethnicity, disability, emotion, or suitability from appearance or body language.</p></div></div><div className="grid gap-4 sm:grid-cols-2">{[["clarity","Clarity"],["roleMotivation","Role motivation"],["communicationStructure","Communication structure"],["customerOrientation","Customer orientation"]].map(([name,label])=><label key={name} className="text-sm font-semibold text-wxIndigo900">{label}<select name={name} defaultValue={String(initialReview?.[name]||"")} required className="mt-2 min-h-11 w-full rounded-md border border-wxBorder bg-wxSurface px-3"><option value="" disabled>Select evidence level</option>{options.map(value=><option key={value} value={value}>{value.replace(/_/g," ")}</option>)}</select></label>)}</div><label className="text-sm font-semibold text-wxIndigo900">Recommendation<select name="recommendation" defaultValue={String(initialReview?.recommendation||"")} required className="mt-2 min-h-11 w-full rounded-md border border-wxBorder bg-wxSurface px-3"><option value="" disabled>Select recommendation</option><option value="continue">Continue</option><option value="hold">Hold for clarification</option><option value="decline">Decline</option></select></label><label className="text-sm font-semibold text-wxIndigo900">Evidence notes<textarea name="notes" defaultValue={String(initialReview?.notes||"")} required minLength={10} rows={4} className="mt-2 w-full rounded-md border border-wxBorder bg-wxSurface p-3" placeholder="Record observable, job-relevant evidence and the reason for the recommendation."/></label><button disabled={busy} className="wx-gradient-action inline-flex min-h-11 items-center justify-center rounded-md px-4 text-sm font-semibold text-white disabled:opacity-60">{busy?"Saving...":"Save human review"}</button>{message?<p role="status" className="text-sm text-wxIndigo600">{message}</p>:null}</form>;
}
