"use client";

import { useState, type FormEvent } from "react";
import { FileUp } from "lucide-react";

export function VerificationDocumentUpload(){
  const[state,setState]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setState("Uploading...");const response=await fetch("/api/admin/hiring/verification-documents",{method:"POST",body:new FormData(event.currentTarget)});const json=await response.json();setState(response.ok?`Stored privately. Scan status: ${json.data.scanStatus}.`:json?.error?.message||"Upload failed.");if(response.ok)event.currentTarget.reset();}
  const classes="mt-2 min-h-11 w-full rounded-md border border-wxBorder bg-white px-3 py-2 text-sm";
  return <form onSubmit={submit} encType="multipart/form-data" className="grid gap-4 rounded-lg border border-wxBorder bg-white p-5 shadow-soft"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-bold">Application reference<input required name="applicationReference" className={classes}/></label><label className="text-sm font-bold">Verification type<select name="verificationType" className={classes}><option value="identity">Identity</option><option value="education">Education</option><option value="background">Background</option><option value="employment">Employment</option><option value="reference">Reference</option></select></label><label className="text-sm font-bold">Document kind<input required name="documentKind" placeholder="Certificate, identity evidence, report..." className={classes}/></label><label className="text-sm font-bold">Private evidence file<input required name="file" type="file" accept="application/pdf,image/jpeg,image/png" className={`${classes} file:mr-3 file:rounded-md file:border-0 file:px-3 file:py-2`}/></label></div><label className="text-sm font-bold">Required access reason<textarea required name="reason" rows={3} className={classes}/></label><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-wxIndigo500">PDF, JPG or PNG only, 10 MB maximum. Private S3, signature checked, malware status remains pending when no provider is configured.</p><button className="inline-flex min-h-11 items-center justify-center gap-2 rounded-md bg-wxViolet700 px-5 font-bold text-white"><FileUp className="h-4 w-4"/>Store private evidence</button></div>{state?<p role="status" className="text-sm text-wxIndigo600">{state}</p>:null}</form>;
}
