"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, ShieldCheck } from "lucide-react";
import { AssessmentWatermark } from "@/components/hiring/AssessmentWatermark";

type Question={questionId:string;version:number;order:number;section:string;category:string;prompt:string;title:string;instructions:string;sourceMaterial:string;answerType:string;expectedTimeMinutes:number;maximumScore:number;required:boolean;backNavigationRule:string;humanReviewRequired:boolean;antiCheatSensitivity:string;vivaFollowUpRequired:boolean;contentHash:string};
type Session={reference:string;applicationReference:string;watermarkReference:string;expiresAt:string;durationMinutes:number;questionCount:number;questions:Question[];accommodation:{extraTimeMinutes:number;questionCopyAllowed:boolean;answerPasteAllowed:boolean;screenReaderMode:boolean;alternateAssessment:boolean;vivaHeavy:boolean;reason?:string};backNavigationAllowed:boolean};

export function AssessmentWorkspace({token,session,antiCheat}:{token:string;session:Session;antiCheat:boolean}){
  const[index,setIndex]=useState(0);const[question,setQuestion]=useState(session.questions[0]);const[answer,setAnswer]=useState("");const[answerCache,setAnswerCache]=useState<Record<string,string>>({});const[savedAt,setSavedAt]=useState("");const[status,setStatus]=useState<"active"|"submitting"|"submitted"|"error">("active");const[message,setMessage]=useState("");const answerRef=useRef("");const timerRef=useRef<ReturnType<typeof setTimeout>|null>(null);
  const logEvent=useCallback((eventType:string,metadata:Record<string,unknown>={})=>{void fetch("/api/hiring/assessment-events",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,eventType,metadata})});},[token]);
  useEffect(()=>{const key=`writex-assessment-open-${session.reference}`;if(sessionStorage.getItem(key))logEvent("page_reload");sessionStorage.setItem(key,"1");const offline=()=>logEvent("disconnection");const online=()=>logEvent("disconnection",{visibilityState:"reconnected"});window.addEventListener("offline",offline);window.addEventListener("online",online);return()=>{window.removeEventListener("offline",offline);window.removeEventListener("online",online);};},[logEvent,session.reference]);
  useEffect(()=>{if(!antiCheat)return;let blurAt=0;const onBlur=()=>{blurAt=Date.now();};const onFocus=()=>{if(blurAt)logEvent("focus_loss",{durationMs:Date.now()-blurAt});blurAt=0;};const onVisibility=()=>logEvent("visibility_change",{visibilityState:document.visibilityState});const onFullscreen=()=>{if(!document.fullscreenElement)logEvent("fullscreen_exit");};window.addEventListener("blur",onBlur);window.addEventListener("focus",onFocus);document.addEventListener("visibilitychange",onVisibility);document.addEventListener("fullscreenchange",onFullscreen);return()=>{window.removeEventListener("blur",onBlur);window.removeEventListener("focus",onFocus);document.removeEventListener("visibilitychange",onVisibility);document.removeEventListener("fullscreenchange",onFullscreen);};},[antiCheat,logEvent]);
  useEffect(()=>()=>{if(timerRef.current)clearTimeout(timerRef.current);},[]);
  async function save(value=answerRef.current){if(!value.trim())return false;const response=await fetch("/api/hiring/assessment-answer",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,questionId:question.questionId,answer:value})});if(response.ok){const payload=await response.json();setSavedAt(payload.data.savedAt);return true;}return false;}
  function change(value:string){if(value.length-answerRef.current.length>120)logEvent("large_insertion",{questionId:question.questionId,characterCount:value.length-answerRef.current.length});answerRef.current=value;setAnswer(value);setAnswerCache(current=>({...current,[question.questionId]:value}));if(timerRef.current)clearTimeout(timerRef.current);timerRef.current=setTimeout(()=>void save(value),1200);}
  function blockProtected(event:React.SyntheticEvent,eventType:string){if(!antiCheat)return;event.preventDefault();logEvent(eventType,{questionId:question.questionId});}
  function blockShortcut(event:React.KeyboardEvent,protectedContent:boolean){const key=event.key.toLowerCase();if(protectedContent&&!session.accommodation.questionCopyAllowed&&(event.metaKey||event.ctrlKey)&&key==="c")blockProtected(event,"copy_attempt");if(!protectedContent&&!session.accommodation.answerPasteAllowed&&(((event.metaKey||event.ctrlKey)&&key==="v")||(event.shiftKey&&event.key==="Insert")))blockProtected(event,"paste_attempt");}
  async function navigate(nextIndex:number){if(!await save()){setStatus("error");setMessage("Enter and save your response before continuing.");return;}const response=await fetch("/api/hiring/assessment-question",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,index:nextIndex})});const payload=await response.json();if(!response.ok){setStatus("error");setMessage(payload?.error?.message||"The requested question could not be released.");return;}const nextQuestion=payload.data.question as Question;const cached=answerCache[nextQuestion.questionId]||"";setQuestion(nextQuestion);setIndex(nextIndex);answerRef.current=cached;setAnswer(cached);setSavedAt("");setStatus("active");}
  async function submit(){setStatus("submitting");if(!await save()){setStatus("error");setMessage("Enter and save your response before submitting.");return;}const response=await fetch("/api/hiring/assessment-submit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token})});const payload=await response.json();if(!response.ok){setStatus("error");setMessage(payload?.error?.message||"Submission failed.");return;}setStatus("submitted");}
  if(status==="submitted")return <section className="mx-auto my-16 max-w-xl rounded-md border border-emerald-200 bg-wxSurface p-7 text-center shadow-soft"><CheckCircle2 className="mx-auto h-10 w-10 text-emerald-600"/><h1 className="mt-4 text-3xl font-bold text-wxIndigo900">Assessment submitted</h1><p className="mt-2 text-sm leading-6 text-wxIndigo500">Your exact answers and question versions are locked. System Review and Admin Review now continue as separate steps.</p></section>;
  const copyAllowed=!antiCheat||session.accommodation.questionCopyAllowed;const pasteAllowed=!antiCheat||session.accommodation.answerPasteAllowed;const allowPrevious=(session.backNavigationAllowed||question.backNavigationRule==="allowed")&&index>0;
  return <div className="relative min-h-screen bg-wxBg p-4 md:p-8"><AssessmentWatermark applicationReference={session.applicationReference} sessionReference={session.reference}/><div className="relative z-10 mx-auto max-w-5xl">
    <header className="flex flex-col gap-3 rounded-md border border-wxBorder bg-wxSurface p-4 shadow-soft sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase text-wxViolet700">{session.reference}</p><p className="mt-1 text-sm text-wxIndigo500">Question {index+1} of {session.questionCount}</p></div><div className="flex items-center gap-2 text-sm font-bold text-wxIndigo900"><Clock3 className="h-4 w-4"/>Ends {new Date(session.expiresAt).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"})}</div></header>
    <main className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1fr)_300px]"><section className="rounded-md border border-wxBorder bg-wxSurface p-6 shadow-soft"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-bold uppercase text-wxIndigo500">{question.section} / {question.category.replace(/_/g," ")}</p><p className="text-xs text-wxIndigo500">{question.expectedTimeMinutes} min / {question.maximumScore} points</p></div><div className={`mt-4 rounded-md bg-wxSurfaceSoft p-5 ${copyAllowed?"":"select-none"}`} tabIndex={0} onCopy={(event)=>{if(!copyAllowed)blockProtected(event,"copy_attempt")}} onKeyDown={(event)=>blockShortcut(event,true)} onContextMenu={(event)=>{if(!copyAllowed)blockProtected(event,"context_menu_attempt")}} onDragStart={(event)=>{if(!copyAllowed)blockProtected(event,"drag_drop_attempt")}}><h1 className="text-xl font-bold leading-8 text-wxIndigo900">{question.title||question.prompt}</h1>{question.title&&question.title!==question.prompt?<p className="mt-3 whitespace-pre-wrap leading-7 text-wxIndigo700">{question.prompt}</p>:null}{question.instructions?<p className="mt-4 border-t border-wxBorder pt-4 text-sm leading-6 text-wxIndigo600">{question.instructions}</p>:null}{question.sourceMaterial?<div className="mt-4 rounded-md border border-wxBorder bg-wxSurface p-4"><p className="text-xs font-bold uppercase text-wxViolet700">Source material</p><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-wxIndigo700">{question.sourceMaterial}</p></div>:null}</div>
      <label className="mt-6 block text-sm font-bold text-wxIndigo900">Your response<textarea value={answer} onChange={(event)=>change(event.target.value)} onKeyDown={(event)=>blockShortcut(event,false)} onPaste={(event)=>{if(!pasteAllowed)blockProtected(event,"paste_attempt")}} onDrop={(event)=>{if(!pasteAllowed)blockProtected(event,"drag_drop_attempt")}} rows={question.answerType==="short_text"?4:12} className="mt-2 w-full rounded-md border border-wxBorder bg-wxSurface p-4 font-normal leading-6 text-wxIndigo900 outline-none focus:border-wxViolet700 focus:ring-2 focus:ring-wxViolet700/20"/></label>
      <div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-wxIndigo500">{savedAt?`Saved ${new Date(savedAt).toLocaleTimeString("en-IN")}`:"Autosave starts when you type."}</p><div className="flex flex-wrap gap-2">{allowPrevious?<button type="button" onClick={()=>void navigate(index-1)} className="min-h-11 rounded-md border border-wxBorder bg-wxSurface px-5 font-bold text-wxIndigo700">Previous</button>:null}{index<session.questionCount-1?<button type="button" onClick={()=>void navigate(index+1)} className="min-h-11 rounded-md bg-wxViolet700 px-5 font-bold text-white">Save and next</button>:<button type="button" onClick={()=>void submit()} disabled={status==="submitting"} className="min-h-11 rounded-md bg-brand-spectrum px-5 font-bold text-white">{status==="submitting"?"Submitting...":"Submit assessment"}</button>}</div></div>{status==="error"?<p role="alert" className="mt-4 text-sm text-red-700">{message}</p>:null}
    </section><aside className="rounded-md border border-wxBorder bg-wxSurface p-5 shadow-soft"><ShieldCheck className="h-6 w-6 text-wxViolet700"/><h2 className="mt-3 font-bold text-wxIndigo900">Assessment integrity</h2><p className="mt-2 text-sm leading-6 text-wxIndigo500">Questions are candidate-specific. Copy, paste, focus and session events are advisory signals for human review.</p><div className="mt-4 flex gap-2 rounded-md bg-amber-50 p-3 text-xs text-amber-900"><AlertTriangle className="h-4 w-4 shrink-0"/>A single event never causes automatic rejection. Accessibility accommodations can be approved and audited.</div>{Object.values(session.accommodation).some(value=>value===true||typeof value==="number"&&value>0)?<div className="mt-3 rounded-md border border-emerald-200 bg-emerald-50 p-3 text-xs leading-5 text-emerald-900">Approved accommodations are active for this session and recorded in the audit trail.</div>:null}</aside></main>
  </div></div>;
}
