import type { EmployeeDirectoryItem, EmployeeTeam } from "@/lib/employees/domain";

export const employeePreviewTeams: EmployeeTeam[] = [
  { id: "10000000-0000-4000-8000-000000000001", teamCode: "SALES-EAST", name: "Sales East", department: "Sales", status: "ACTIVE" },
  { id: "10000000-0000-4000-8000-000000000002", teamCode: "OPS-DELIVERY", name: "Delivery Operations", department: "Operations", status: "ACTIVE" }
];

export const employeePreviewItems: EmployeeDirectoryItem[] = [
  {
    id: "20000000-0000-4000-8000-000000000001",
    employeeCode: "WX-SALES-014",
    displayName: "Ananya Sen",
    officialEmail: "ananya.sen@example.test",
    department: "Sales",
    designation: "Team Lead",
    employmentStatus: "ACTIVE",
    primaryTeamId: employeePreviewTeams[0].id,
    teamName: "Sales East",
    managerEmployeeId: null,
    managerName: null,
    academyEnabled: true,
    academyRole: "MANAGER_TL",
    primarySuperAdmin: false,
    employeeSegment: "SENIOR_BDE",
    syncStatus: "SYNCED",
    lastSyncedAt: "2026-08-13T08:30:00.000Z",
    lastSyncError: null,
    academyUserId: "academy-preview-manager",
    archivedAt: null,
    archivePreviousEmploymentStatus: null,
    archivePreviousAcademyEnabled: null,
    lifecycleVersion: 1,
    updatedAt: "2026-08-13T08:30:00.000Z"
  },
  {
    id: "20000000-0000-4000-8000-000000000002",
    employeeCode: "WX-SALES-027",
    displayName: "Rohan Das",
    officialEmail: "rohan.das@example.test",
    department: "Sales",
    designation: "Sales Executive",
    employmentStatus: "ACTIVE",
    primaryTeamId: employeePreviewTeams[0].id,
    teamName: "Sales East",
    managerEmployeeId: "20000000-0000-4000-8000-000000000001",
    managerName: "Ananya Sen",
    academyEnabled: true,
    academyRole: "EMPLOYEE",
    primarySuperAdmin: false,
    employeeSegment: "SENIOR_BDE",
    syncStatus: "FAILED",
    lastSyncedAt: null,
    lastSyncError: "ACADEMY_UNAVAILABLE: Academy is temporarily unavailable. The requested change is saved and can be retried.",
    academyUserId: "academy-preview-employee",
    archivedAt: null,
    archivePreviousEmploymentStatus: null,
    archivePreviousAcademyEnabled: null,
    lifecycleVersion: 1,
    updatedAt: "2026-08-13T08:32:00.000Z"
  },
  {
    id: "20000000-0000-4000-8000-000000000003",
    employeeCode: "WX-OPS-009",
    displayName: "Meera Kapoor",
    officialEmail: "meera.kapoor@example.test",
    department: "Operations",
    designation: "Quality Specialist",
    employmentStatus: "INACTIVE",
    primaryTeamId: employeePreviewTeams[1].id,
    teamName: "Delivery Operations",
    managerEmployeeId: null,
    managerName: null,
    academyEnabled: false,
    academyRole: "EMPLOYEE",
    primarySuperAdmin: false,
    employeeSegment: "SENIOR_BDE",
    syncStatus: "SYNCED",
    lastSyncedAt: "2026-08-12T17:15:00.000Z",
    lastSyncError: null,
    academyUserId: "academy-preview-inactive",
    archivedAt: null,
    archivePreviousEmploymentStatus: null,
    archivePreviousAcademyEnabled: null,
    lifecycleVersion: 1,
    updatedAt: "2026-08-12T17:15:00.000Z"
  },
  {
    id: "20000000-0000-4000-8000-000000000004",
    employeeCode: "WX-UAT-ARCHIVED",
    displayName: "Archived UAT Employee",
    officialEmail: "archived-uat@example.test",
    department: "Sales",
    designation: "Sales Executive",
    employmentStatus: "INACTIVE",
    primaryTeamId: employeePreviewTeams[0].id,
    teamName: "Sales East",
    managerEmployeeId: null,
    managerName: null,
    academyEnabled: false,
    academyRole: "EMPLOYEE",
    primarySuperAdmin: false,
    employeeSegment: "NEW_BDE",
    syncStatus: "SYNCED",
    lastSyncedAt: "2026-08-13T07:15:00.000Z",
    lastSyncError: null,
    academyUserId: "academy-preview-archived",
    archivedAt: "2026-08-13T07:30:00.000Z",
    archivePreviousEmploymentStatus: "ACTIVE",
    archivePreviousAcademyEnabled: true,
    lifecycleVersion: 3,
    updatedAt: "2026-08-13T07:30:00.000Z"
  }
];
